name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test secrets
        run: |
          echo "Testing if secrets are set..."
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then echo "✓ VERCEL_TOKEN is set"; else echo "✗ VERCEL_TOKEN is not set"; fi
          if [ -n "${{ secrets.VERCEL_ORG_ID }}" ]; then echo "✓ VERCEL_ORG_ID is set"; else echo "✗ VERCEL_ORG_ID is not set"; fi
          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then echo "✓ VERCEL_PROJECT_ID is set"; else echo "✗ VERCEL_PROJECT_ID is not set"; fi
          if [ -n "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ]; then echo "✓ NEXT_PUBLIC_SUPABASE_URL is set"; else echo "✗ NEXT_PUBLIC_SUPABASE_URL is not set"; fi
          if [ -n "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" ]; then echo "✓ NEXT_PUBLIC_SUPABASE_ANON_KEY is set"; else echo "✗ NEXT_PUBLIC_SUPABASE_ANON_KEY is not set"; fi